const languages = {
    "en": {
      "filterBtnLabel": "Filters",
      "taxesSwitchLabel": "Display total before taxes",
      "stays": "stays",
      "experiences": "experiences",
      "log_in": "log in",
      "sign_up": "sign up",
      "gift_cards": "gift cards",
      "airbnb_your_home": "airbnb your home",
      "Wishlist": "Wishlist",
      "Trips": "Trips",
      "host_exp": "host an experience",
      "messages":"Messages",
      "account": "Account",
      "help_center": "help center",
      "who": "who",
      "addGuests": "add guests",
      "checkOut": "check out",
      "addDate": "add date",
      "checkIn": "check in",
      "where": "where",
      "Where_to":"Where to?",

      "searchDest": "Search Destinations",
      "lovedBnb": "One of the most loved homes on Airbnb, according to guests",
      "reviews": "Reviews",
      "hosted": "Hosted by Piavi",
      "hostSpan": "3 months hosting",
      "roomInHome": "Your own room in a home, plus access to shared spaces.",
      "sharedSpaces": "You’ll share parts of the home with other guests.",
      "prvSpace": "This place has a bathroom that’s connected to your room.",
      "grtExp": "100% of recent guests gave the check-in process a 5-star rating.",
      "guestFav": "Guest favorite",
      "oneOfMost": "One of the most loved homes on Airbnb based on ratings, reviews, and reliability",
      "ovrAll": "Overall rating",
      "clean": "Cleanliness",
      "accuracy": "Accuracy",
      "check-in": "Check-in",
      "comm": "Communication",
      "loc": "Location",
      "val": "Value",
      "entire": "Entire",
      "in": "in",
      "guests": "guests",
      "bedrooms": "bedrooms",
      "beds": "beds",
      "baths": "baths",
      "night": "night",
      "adults": "Adults",
      "children": "Children",
      "infants": "Infants",
      "pet": "Pet",
      "notCharged": "You won't be charged yet",
      "totalBefore": "Total before taxes",
      "reserve": "Reserve",
      "showAll": "Show all photos",
      "log_out": "Log out",
      "new_roomInHome": "Room in a home", 
      "new_sharedSpaces": "Shared common spaces",
      "new_prvSpace": "Private attached bathroom",
      "new_grtExp": "Great check-in experience",
      "lockOnDoor": "Lock on bedroom door",
    "wifi": "Wifi",
    "petsAllowed": "Pets allowed",
    "airConditioning": "Air conditioning",
    "longTermStays": "Long-term stays allowed",
    "lakeAccess": "Lake access",
    "freeParking": "Free parking on premises",
    "tv": "TV",
    "securityCameras": "Security cameras on property",
    "cleaningAvailable": "Cleaning available during stay",
    "whatThisPlaceOffers": "What this place offers",
    "showAllAmenities": "Show All Amenities",
    "meetYourHost": "Meet your Host",
    "rating": "Rating",
    "hosting": "Hosting",
    "years": "Years",
    "speaks": "Speaks English, French and Hindi",
    "livesIn": "Lives in Jaipur, India",
    "hostBio": "Hi All, I am Piava Jain C/O Le Pensions Stays & Enterprises Pvt Ltd. By qualification, I am a chartered Accountant from The Institute of Chartered Accountants of India. But at heart, I have always been an entrepreneur. Our team has a collective experience of more than 24 years in hospitality and we love what we do. Le Pension...",
        "anywhere": "Anywhere",
    "anyWeek": "Any week",
    "addGuests": "Add guests",
    "privacy": "Privacy",
    "terms": "Terms",
    "siteMap": "Site map",
    "chooseLangRegion": "Choose a language and region",
    "explore":"Explore",
    "confirmAndPay": "Confirm and Pay",
    "yourTrip": "Your trip",
    "dates": "Dates",
    "payWith": "Pay with",
    "nonRefundable": "Non-refundable",
    "nonRefundableNote": "This reservation is non-refundable.",
    "groundRules": "Ground rules",
    "groundRulesNote": "We ask every guest to remember a few simple things about what makes a great guest.",
    "priceDetails": "Price Details",
    "longStayDiscount": "Long stay discount",
    "total": "Total"
},
    "ar": {
        "confirmAndPay": "تأكيد والدفع",
    "yourTrip": "رحلتك",
    "dates": "التواريخ",
    "payWith": "الدفع باستخدام",
    "nonRefundable": "غير قابل للاسترداد",
    "nonRefundableNote": "هذه الحجز غير قابل للاسترداد.",
    "groundRules": "قواعد أساسية",
    "groundRulesNote": "نطلب من كل ضيف أن يتذكر بعض الأشياء البسيطة حول ما يجعل الضيف جيدًا.",
    "priceDetails": "تفاصيل السعر",
    "longStayDiscount": "خصم الإقامة الطويلة",
    "total": "الإجمالي",
        "Where_to":"الى اين؟",
        "messages":"رسائل",
      "account": "الحساب",
        "explore":"أستكشاف",
        "chooseLangRegion": "اختر لغة ومنطقة",
      "filterBtnLabel": "عوامل التصفية",
      "log_out": "تسجيل الخروج",
      "taxesSwitchLabel": "عرض الإجمالي قبل الضرائب",
      "stays": "الإقامات",
      "experiences": "التجارب",
      "log_in": "تسجيل الدخول",
      "sign_up": "إنشاء حساب",
      "Wishlist": "مختاراتك المفضلة",
      "Trips": "الرحلات",
      "gift_cards": "بطاقات الهدايا",
      "airbnb_your_home": "سعر منزلك",
      "host_exp": "استضافة تجربة",
      "help_center": "مركز المساعدة",
      "who": "من",
      "addGuests": "إضافة ضيوف",
      "checkOut": "تسجيل المغادرة",
      "addDate": "إضافة تاريخ",
      "checkIn": "تسجيل الوصول",
      "where": "أين",
      "searchDest": "البحث عن الوجهات",
      "lovedBnb": "واحدة من أكثر المنازل المحبوبة على Airbnb وفقًا للضيوف",
      "reviews": "المراجعات",
      "hosted": "استضافه بيافي",
      "hostSpan": "3 أشهر من الاستضافة",
      "roomInHome": "غرفتك الخاصة في المنزل، بالإضافة إلى الوصول إلى المساحات المشتركة.",
      "sharedSpaces": "ستشارك أجزاء من المنزل مع ضيوف آخرين.",
      "prvSpace": "يوجد حمام متصل بغرفتك.",
      "grtExp": "100٪ من الضيوف حديثي الحجز قيموا عملية تسجيل الوصول بـ 5 نجوم.",
      "guestFav": "مفضل الضيوف",
      "oneOfMost": "واحدة من أكثر المنازل المحبوبة على Airbnb بناءً على التقييمات والمراجعات والموثوقية",
      "ovrAll": "التقييم العام",
      "clean": "النظافة",
      "accuracy": "الدقة",
      "check_in": "تسجيل الوصول",
      "comm": "الاتصال",
      "loc": "الموقع",
      "val": "القيمة",
      "entire": "منزل كامل",
      "in": "في",
      "guests": "ضيوف",
      "bedrooms": "غرف النوم",
      "beds": "أسرة",
      "baths": "حمامات",
      "night": "ليلة",
      "adults": "البالغون",
      "children": "الأطفال",
      "infants": "الرضع",
      "pet": "حيوان أليف",
      "notCharged": "لن يتم تحصيل رسوم بعد",
      "totalBefore": "الإجمالي قبل الضرائب",
      "reserve": "احجز",
      "showAll": "عرض جميع الصور",
      "new_roomInHome": "غرفة في المنزل",
      "new_sharedSpaces": "مساحات مشتركة",
      "new_prvSpace": "حمام خاص متصل",
      "new_grtExp": "تجربة تسجيل وصول رائعة",
      "lockOnDoor": "قفل على باب غرفة النوم",
        "wifi": "واي فاي",
        "petsAllowed": "مسموح بالحيوانات الأليفة",
        "airConditioning": "تكييف الهواء",
        "longTermStays": "الإقامات الطويلة مسموح بها",
        "lakeAccess": "الوصول إلى البحيرة",
        "freeParking": "موقف سيارات مجاني في الموقع",
        "tv": "تلفاز",
        "securityCameras": "كاميرات مراقبة في العقار",
        "cleaningAvailable": "التنظيف متاح أثناء الإقامة",
        "whatThisPlaceOffers": "ما يقدمه هذا المكان",
    "showAllAmenities": "عرض جميع وسائل الراحة",
    "meetYourHost": "تعرف على المضيف",
    "rating": "التقييم",
    "hosting": "الاستضافة",
    "years": "سنوات",
    "anywhere": "أي مكان",
    "anyWeek": "أي أسبوع",
    "addGuests": "إضافة ضيوف",
    "speaks": "يتحدث الإنجليزية، الفرنسية والهندية",
    "livesIn": "يعيش في جايبور، الهند",
    "hostBio": "مرحبًا جميعًا، أنا بيافا جاين من شركة Le Pensions Stays & Enterprises Pvt Ltd. بحكم المؤهلات، أنا محاسب قانوني من معهد المحاسبين القانونيين في الهند. ولكن في القلب، كنت دائمًا رائدة أعمال. يتمتع فريقنا بخبرة جماعية تزيد عن 24 عامًا في مجال الضيافة ونحب ما نقوم به. Le Pension...",
    "privacy": "الخصوصية",
    "terms": "الشروط",
    "siteMap": "خريطة الموقع"
}
  };
  
  export default languages;
  